### ISSUE TITLE
AttributeError: 'list' object has no attribute 'copy' on Pass 97/98

### ISSUE THREAD

**Issue by OffBy0x01** [ChrisTheCoolHut/Rocket-Shot#1]
I am consistently getting this error on Initial Pass 97/98:

```
Traceback (most recent call last):
  File "rocket_shot.py", line 525, in <module>
    main()
  File "rocket_shot.py", line 479, in main
    nodes_list = get_predecessors(nodes_list)
  File "rocket_shot.py", line 181, in get_predecessors
    path_stitch = node_list.copy()
AttributeError: 'list' object has no attribute 'copy'

```
I assumed in your usage example where you have "python rocket_shot.py <challenge>", _python_ is python2. If that is the case, the list.copy method wasn't introduced until python3 so you will have to use list slicing:
`node_list_copy = node_list[:]`
or some other method to copy it.

If I implement the [:] copy fix I end up running into an IndexError:
```
Traceback (most recent call last):
  File "rocket_shot.py", line 526, in <module>
    main()
  File "rocket_shot.py", line 508, in main
    nodes_list.remove(nodes_list[item_index])
IndexError: list index out of range
```

I've not investigated any further than that

**Comment by ChrisTheCoolHut** [comment]
I just pushed this [commit](https://github.com/ChrisTheCoolHut/Rocket-Shot/commit/bb3602c8506ed0b40ab560515babd26f497090e4), please pull and try it now.

**Comment by AR-Calder** [comment]
That fixed it, all working now!

**Comment by OffBy0x01** [comment]
That fixed it, all working now!

Just in case it is of interest, your both the script and installer work on Fedora 28+
